// 客户端类型配置
export const CLIENT_TYPES = {
  "Clash.Meta / Clash Verge": "clash-meta",
  "Clash（旧版）": "clash",
  Surge: "surge&ver=4",
  Quantumult: "quan",
  QuantumultX: "quanx",
  Mellow: "mellow",
  Surfboard: "surfboard",
  Loon: "loon",
  singbox: "singbox",
  ss: "ss",
  ssd: "ssd",
  sssub: "sssub",
  ssr: "ssr",
  ClashR: "clashr",
  V2Ray: "v2ray",
  Trojan: "trojan",
  Surge3: "surge&ver=3",
};
